"""
Django settings for scambio_sito project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-z#j7++ie89nsi-8+ca#xxtqglv#=(90^&lilla*!=j^(8ycg89')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'scambi',
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'scambi.backends.EmailOrUsernameModelBackend',  # Login con username o email
    'django.contrib.auth.backends.ModelBackend',     # Fallback standard
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scambio_sito.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scambi.views.context_processor_notifiche',
            ],
        },
    },
]

WSGI_APPLICATION = 'scambio_sito.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Inizializza esplicitamente il modulo cloudinary base
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
    secure=True
)

# Cloudinary Content Moderation
# Attiva moderazione automatica con AWS Rekognition
CLOUDINARY_MODERATION_ENABLED = os.environ.get('CLOUDINARY_MODERATION_ENABLED', 'True') == 'True'
CLOUDINARY_MODERATION_KIND = 'aws_rek'  # AWS Rekognition per content moderation

# Site URL per webhook (necessario per notification_url di Cloudinary)
SITE_URL = os.environ.get('SITE_URL', 'https://polygonum.onrender.com')

# DEBUG: Verifica variabili ambiente Cloudinary
print("=" * 60)
print("DEBUG - Cloudinary Environment Variables:")
print(f"  CLOUDINARY_CLOUD_NAME: {os.environ.get('CLOUDINARY_CLOUD_NAME', 'NOT SET')}")
print(f"  CLOUDINARY_API_KEY: {'***' + os.environ.get('CLOUDINARY_API_KEY', 'NOT SET')[-4:] if os.environ.get('CLOUDINARY_API_KEY') else 'NOT SET'}")
print(f"  CLOUDINARY_API_SECRET: {'SET' if os.environ.get('CLOUDINARY_API_SECRET') else 'NOT SET'}")
print(f"  RENDER env var: {os.environ.get('RENDER', 'NOT SET')}")
print(f"  CLOUDINARY_STORAGE dict: {CLOUDINARY_STORAGE}")
print(f"  cloudinary.config() chiamato: ✓")
print("=" * 60)

# Media files (uploaded by users)
# In produzione usa Cloudinary, in locale usa filesystem
if os.environ.get('RENDER') or os.environ.get('CLOUDINARY_CLOUD_NAME'):
    # Produzione: usa Cloudinary
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # IMPORTANTE: NON impostare MEDIA_URL quando usi Cloudinary!
    # Cloudinary genera automaticamente i suoi URL completi
    print("☁️  Using Cloudinary for media storage")
    print(f"☁️  DEFAULT_FILE_STORAGE = {DEFAULT_FILE_STORAGE}")
else:
    # Sviluppo locale: usa filesystem
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print("💾 Using local filesystem for media storage")
    print(f"💾 MEDIA_ROOT = {MEDIA_ROOT}")

# Dimensioni massime per upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Email settings
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'polygonum.noreply@gmail.com')

# Email backend logic
if os.environ.get('SENDGRID_API_KEY'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    print(f"📧 Using SMTP backend with SendGrid API key")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print(f"📧 Using console backend (no SendGrid API key)")

# Email verification settings
EMAIL_VERIFICATION_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL rimosso - ora usiamo il template logout.html

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'scambi': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Production settings
if os.environ.get('RENDER'):
    DEBUG = False
    ALLOWED_HOSTS = ['.onrender.com']

    # Database in production
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }

    # Static files in production
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    # HTTPS and Security settings for production
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # CSRF settings for HTTPS
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

    # Session security
    SESSION_COOKIE_SECURE = True

    # Email configuration is already set above based on SENDGRID_API_KEY
    # No need to override EMAIL_BACKEND here
