# Generated by Django 5.2.6 on 2025-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='annunci/'),
        ),
    ]
