# Generated by Django 5.2.6 on 2025-09-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0002_annuncio_immagine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=50, verbose_name='Provincia')),
                ('regione', models.CharField(blank=True, max_length=50, verbose_name='Regione')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utenti',
            },
        ),
    ]
