# Generated by Django 5.2.6 on 2025-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citta',
            field=models.CharField(max_length=100, verbose_name='Città'),
        ),
    ]
