# Generated by Django 5.2.6 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0005_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='distanza_massima_km',
            field=models.IntegerField(blank=True, help_text='Solo per scambi a mano. Lascia vuoto se disponibile per spedizione', null=True, verbose_name='Distanza massima per scambio a mano (km)'),
        ),
        migrations.AddField(
            model_name='annuncio',
            name='metodo_scambio',
            field=models.CharField(choices=[('entrambi', 'Scambio a mano o spedizione'), ('mano', 'Solo scambio a mano'), ('spedizione', 'Solo spedizione')], default='entrambi', max_length=15, verbose_name='Metodo di scambio preferito'),
        ),
        migrations.AddField(
            model_name='annuncio',
            name='prezzo_stimato',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valore indicativo dell'oggetto per facilitare scambi equi", max_digits=10, null=True, verbose_name='Prezzo stimato (€)'),
        ),
    ]
