# Generated by Django 5.2.6 on 2025-10-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0006_annuncio_distanza_massima_km_annuncio_metodo_scambio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuova_catena', 'Nuova catena di scambio disponibile'), ('preferito_aggiunto', 'Il tuo annuncio è stato aggiunto ai preferiti'), ('proposta_scambio', 'Nuova proposta di scambio'), ('benvenuto', 'Messaggio di benvenuto'), ('sistema', 'Notifica di sistema')], max_length=20)),
                ('titolo', models.CharField(max_length=200)),
                ('messaggio', models.TextField()),
                ('letta', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('url_azione', models.URLField(blank=True, help_text='URL per azione della notifica', null=True)),
                ('annuncio_collegato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scambi.annuncio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
                ('utente_collegato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_generate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='PropostaScambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField(blank=True, help_text='Messaggio opzionale dal richiedente')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa di risposta'), ('accettata', 'Accettata'), ('rifiutata', 'Rifiutata'), ('completata', 'Scambio completato')], default='in_attesa', max_length=15)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_risposta', models.DateTimeField(blank=True, null=True)),
                ('annuncio_offerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_come_offerto', to='scambi.annuncio')),
                ('annuncio_richiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_come_richiesto', to='scambi.annuncio')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_ricevute', to=settings.AUTH_USER_MODEL)),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_inviate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta di Scambio',
                'verbose_name_plural': 'Proposte di Scambio',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Preferiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('annuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferito_da', to='scambi.annuncio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferiti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferito',
                'verbose_name_plural': 'Preferiti',
                'ordering': ['-data_aggiunta'],
                'unique_together': {('utente', 'annuncio')},
            },
        ),
    ]
