# Generated by Django 5.2.6 on 2025-10-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0007_notifica_propostascambio_preferiti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privata', 'Conversazione Privata'), ('gruppo', 'Chat di Gruppo')], default='privata', max_length=10)),
                ('nome', models.CharField(blank=True, help_text='Nome della chat di gruppo', max_length=200)),
                ('catena_scambio_id', models.CharField(blank=True, help_text='ID della catena di scambio', max_length=100, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ultimo_messaggio', models.DateTimeField(auto_now_add=True)),
                ('utenti', models.ManyToManyField(related_name='conversazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversazione',
                'verbose_name_plural': 'Conversazioni',
                'ordering': ['-ultimo_messaggio'],
            },
        ),
        migrations.CreateModel(
            name='CatenaScambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catena_id', models.CharField(help_text='ID univoco della catena', max_length=100, unique=True)),
                ('nome', models.CharField(help_text='Nome descrittivo della catena', max_length=200)),
                ('descrizione', models.TextField(blank=True, help_text='Descrizione degli scambi nella catena')),
                ('dati_catena', models.JSONField(help_text='Dati completi della catena dal sistema di matching')),
                ('stato', models.CharField(choices=[('proposta', 'Proposta'), ('attiva', 'Attiva'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='proposta', max_length=15)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_attivazione', models.DateTimeField(blank=True, null=True)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('utente_attivatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catene_attivate', to=settings.AUTH_USER_MODEL)),
                ('conversazione', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scambi.conversazione')),
            ],
            options={
                'verbose_name': 'Catena di Scambio',
                'verbose_name_plural': 'Catene di Scambio',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='LetturaMessaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lettura', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lettura Messaggio',
                'verbose_name_plural': 'Letture Messaggi',
            },
        ),
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('is_sistema', models.BooleanField(default=False)),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('conversazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi', to='scambi.conversazione')),
                ('letto_da', models.ManyToManyField(related_name='messaggi_letti', through='scambi.LetturaMessaggio', to=settings.AUTH_USER_MODEL)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
                'ordering': ['data_invio'],
            },
        ),
        migrations.AddField(
            model_name='letturamessaggio',
            name='messaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scambi.messaggio'),
        ),
        migrations.CreateModel(
            name='PartecipazioneScambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('invitato', 'Invitato'), ('accettato', 'Accettato'), ('completato', 'Completato'), ('rifiutato', 'Rifiutato')], default='invitato', max_length=15)),
                ('data_partecipazione', models.DateTimeField(auto_now_add=True)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('annuncio_da_dare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scambi_dare', to='scambi.annuncio')),
                ('annuncio_da_ricevere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scambi_ricevere', to='scambi.annuncio')),
                ('catena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scambi.catenascambio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partecipazione Scambio',
                'verbose_name_plural': 'Partecipazioni Scambi',
                'unique_together': {('catena', 'utente')},
            },
        ),
        migrations.AddField(
            model_name='catenascambio',
            name='partecipanti',
            field=models.ManyToManyField(related_name='catene_partecipate', through='scambi.PartecipazioneScambio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='letturamessaggio',
            unique_together={('messaggio', 'utente')},
        ),
    ]
