# Generated by Django 5.2.6 on 2025-10-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0008_conversazione_catenascambio_letturamessaggio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatenaPreferita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catena_hash', models.CharField(help_text='Hash unico della catena basato sui partecipanti', max_length=64)),
                ('catena_data', models.JSONField(help_text='Dati completi della catena per visualizzazione')),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('tipo_catena', models.CharField(choices=[('scambio_diretto', 'Scambio Diretto'), ('catena_lunga', 'Catena Lunga')], max_length=20)),
                ('categoria_qualita', models.CharField(choices=[('alta', 'Alta Qualità'), ('generica', 'Generica')], max_length=20)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catene_preferite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catena Preferita',
                'verbose_name_plural': 'Catene Preferite',
                'ordering': ['-data_aggiunta'],
                'unique_together': {('utente', 'catena_hash')},
            },
        ),
    ]
