# Generated by Django 5.2.6 on 2025-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0009_catenapreferita'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloScambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.JSONField(help_text='Array ordinato di user_id che formano il ciclo')),
                ('lunghezza', models.IntegerField(help_text='Numero di utenti nel ciclo')),
                ('dettagli', models.JSONField(help_text='Dettagli completi del ciclo: annunci, oggetti, compatibilità')),
                ('calcolato_at', models.DateTimeField(auto_now=True, help_text="Timestamp dell'ultimo calcolo")),
                ('valido', models.BooleanField(default=True, help_text='Indica se il ciclo è ancora valido (annunci attivi)')),
                ('hash_ciclo', models.CharField(help_text='Hash MD5 del ciclo per rilevare duplicati', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Ciclo di Scambio',
                'verbose_name_plural': 'Cicli di Scambio',
                'ordering': ['lunghezza', '-calcolato_at'],
                'indexes': [models.Index(fields=['valido', 'lunghezza'], name='scambi_cicl_valido_818f76_idx'), models.Index(fields=['calcolato_at'], name='scambi_cicl_calcola_6c5753_idx'), models.Index(fields=['hash_ciclo'], name='scambi_cicl_hash_ci_33fa8a_idx')],
            },
        ),
    ]
