# Generated by Django 5.2.6 on 2025-10-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0010_add_cicloscambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('regione', models.CharField(max_length=50)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Città',
                'verbose_name_plural': 'Città',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='citta',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citta_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città (vecchio)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citta_obj',
            field=models.ForeignKey(blank=True, help_text='Seleziona la tua città dal menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scambi.citta', verbose_name='Città'),
        ),
        migrations.CreateModel(
            name='DistanzaCitta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanza_km', models.IntegerField(help_text='Distanza in km tra le due città')),
                ('citta_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distanze_da', to='scambi.citta')),
                ('citta_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distanze_a', to='scambi.citta')),
            ],
            options={
                'verbose_name': 'Distanza tra Città',
                'verbose_name_plural': 'Distanze tra Città',
                'unique_together': {('citta_a', 'citta_b')},
            },
        ),
    ]
