# Generated by Django 5.2.6 on 2025-10-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0011_citta_remove_userprofile_citta_userprofile_citta_old_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaCatena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('tutti_interessati', 'Tutti interessati'), ('rifiutata', 'Rifiutata'), ('annullata', 'Annullata')], default='in_attesa', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_aggiornamento', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte', to='scambi.cicloscambio')),
                ('iniziatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_catena_iniziate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta Catena',
                'verbose_name_plural': 'Proposte Catene',
                'ordering': ['-data_creazione'],
                'unique_together': {('ciclo', 'iniziatore')},
            },
        ),
        migrations.CreateModel(
            name='RispostaProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta', models.CharField(choices=[('in_attesa', 'In attesa'), ('interessato', 'Interessato'), ('non_interessato', 'Non interessato')], default='in_attesa', max_length=20)),
                ('data_risposta', models.DateTimeField(blank=True, null=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='scambi.propostacatena')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte_proposte_catena', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risposta Proposta',
                'verbose_name_plural': 'Risposte Proposte',
                'ordering': ['data_risposta'],
                'unique_together': {('proposta', 'utente')},
            },
        ),
    ]
