# Generated by Django 5.2.6 on 2025-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0012_propostacatena_rispostaproposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('nuova_catena', 'Nuova catena di scambio disponibile'), ('preferito_aggiunto', 'Il tuo annuncio è stato aggiunto ai preferiti'), ('proposta_scambio', 'Nuova proposta di scambio'), ('proposta_catena', 'Qualcuno è interessato a una catena'), ('risposta_proposta_catena', 'Qualcuno ha risposto alla tua proposta'), ('tutti_interessati', 'Tutti sono interessati alla catena'), ('proposta_rifiutata', 'Qualcuno ha rifiutato la proposta'), ('benvenuto', 'Messaggio di benvenuto'), ('sistema', 'Notifica di sistema')], max_length=30),
        ),
    ]
