# Generated by Django 5.2.6 on 2025-10-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0013_alter_notifica_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostacatena',
            name='data_scadenza',
            field=models.DateTimeField(blank=True, help_text='Data di scadenza della proposta (auto-calcolata: creazione + 7 giorni)', null=True),
        ),
        migrations.AddField(
            model_name='propostacatena',
            name='reminder_inviato',
            field=models.BooleanField(default=False, help_text='Indica se il reminder di scadenza è stato inviato'),
        ),
    ]
