# Generated by Django 5.2.6 on 2025-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0014_propostacatena_data_scadenza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcoloMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, unique=True)),
                ('ultimo_calcolo_completo', models.DateTimeField(help_text="Timestamp dell'ultimo calcolo completo di tutti i cicli")),
                ('cicli_calcolati', models.IntegerField(default=0)),
                ('durata_calcolo_secondi', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Metadata Calcolo',
                'verbose_name_plural': 'Metadata Calcoli',
            },
        ),
        migrations.AddField(
            model_name='annuncio',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modifica'),
        ),
    ]
