# Generated by Django 5.2.6 on 2025-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0015_calcolometadata_annuncio_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Utente Premium'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_scadenza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scadenza Premium'),
        ),
    ]
