# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0020_clean_old_broken_images'),
    ]

    operations = [
        # Campi moderazione per Annuncio
        migrations.AddField(
            model_name='annuncio',
            name='moderation_status',
            field=models.CharField(
                choices=[('pending', 'In revisione'), ('approved', 'Approvato'), ('rejected', 'Rifiutato')],
                default='pending',
                help_text='Stato della revisione automatica del contenuto',
                max_length=20,
                verbose_name='Stato moderazione'
            ),
        ),
        migrations.AddField(
            model_name='annuncio',
            name='moderation_response',
            field=models.JSONField(
                blank=True,
                help_text='Dati completi dalla moderazione Cloudinary',
                null=True,
                verbose_name='Risultati moderazione'
            ),
        ),
        migrations.AddField(
            model_name='annuncio',
            name='moderation_labels',
            field=models.JSONField(
                blank=True,
                help_text='Categorie problematiche rilevate (nudity, violence, etc)',
                null=True,
                verbose_name='Etichette rilevate'
            ),
        ),
        migrations.AddField(
            model_name='annuncio',
            name='moderated_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Quando è stata completata la moderazione automatica',
                null=True,
                verbose_name='Data moderazione'
            ),
        ),

        # Sistema strike e ban per UserProfile
        migrations.AddField(
            model_name='userprofile',
            name='content_strikes',
            field=models.IntegerField(
                default=0,
                help_text='Numero di violazioni per contenuto inappropriato',
                verbose_name='Strike contenuto'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(
                default=False,
                verbose_name='Utente bannato'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data ban'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(
                blank=True,
                help_text='Descrizione del motivo del ban',
                verbose_name='Motivo ban'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_until',
            field=models.DateTimeField(
                blank=True,
                help_text='Data di fine sospensione temporanea',
                null=True,
                verbose_name='Sospeso fino a'
            ),
        ),
    ]
