# Generated by Django 5.2.6 on 2026-03-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0025_aggiungi_fascia_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_enabled',
            field=models.BooleanField(default=True, help_text='Vuoi ricevere email dalla community Polygonum?', verbose_name='Ricevi Newsletter'),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='url_azione',
            field=models.CharField(blank=True, help_text='URL o path relativo per azione della notifica', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='citta',
            field=models.CharField(blank=True, help_text='Nome della tua città o comune (opzionale ma consigliato)', max_length=100, verbose_name='Città/Comune'),
        ),
    ]
