# Generated by Django 5.2.6 on 2026-06-09 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0026_userprofile_newsletter_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggio',
            name='contenuto',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
