# Generated by Django 5.2.6 on 2026-06-17 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scambi', '0027_alter_messaggio_contenuto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostacatena',
            name='stato',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('tutti_interessati', 'Tutti interessati'), ('completata', 'Scambio completato'), ('rifiutata', 'Rifiutata'), ('annullata', 'Annullata')], default='in_attesa', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfermaCompletamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conferma', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferme_completamento', to='scambi.propostacatena')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferme_completamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conferma Completamento',
                'verbose_name_plural': 'Conferme Completamento',
                'unique_together': {('proposta', 'utente')},
            },
        ),
        migrations.CreateModel(
            name='ValutazioneScambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_oggetto', models.PositiveSmallIntegerField(help_text='Corrispondenza tra oggetto ricevuto e descrizione (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comunicazione', models.PositiveSmallIntegerField(help_text='Facilità di comunicazione (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('velocita_risposta', models.PositiveSmallIntegerField(help_text='Velocità nella risposta (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento', models.TextField(blank=True, max_length=1000)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni', to='scambi.propostacatena')),
                ('valutato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni_ricevute', to=settings.AUTH_USER_MODEL)),
                ('valutatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni_date', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valutazione Scambio',
                'verbose_name_plural': 'Valutazioni Scambi',
                'unique_together': {('proposta', 'valutatore', 'valutato')},
            },
        ),
    ]
