name: Daily Expiration Check

on:
  schedule:
    # Esegui ogni giorno alle 2:00 AM UTC (3:00 AM CET in inverno, 4:00 AM CEST in estate)
    - cron: '0 2 * * *'
  workflow_dispatch: # Permette esecuzione manuale

jobs:
  check-expirations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check proposal expirations
      run: |
        python manage.py gestisci_scadenze_proposte
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: 'False'
        RENDER: 'True'
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
